milvus:
  host: "localhost"
  port: 19530

index_params:
  metric_type: "COSINE"
  index_type: "IVF_FLAT"
  params:
    nlist: 256

search_params:
  metric_type: "COSINE"
  offset: 0
  ignore_growing: False
  params:
    nprobe: 20

database:
  database_name: "Products"
  products_collection: "products"
  images_collection: 'images'

model_name: 'open_clip:ViT-B-16'
